import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/sidebar';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';

import './globals.css';
import DndProvider from '@/providers/dnd-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          'h-[100dvh] bg-background overflow-hidden dark',
        )}
      >
        <DndProvider>
          <div className="relative flex h-full w-full bg-background text-foreground">
            <Sidebar />
            <div className="relative z-10 bg-background flex flex-1 flex-col overflow-x-hidden">
              <Header />
              <main className="flex-1 overflow-auto min-w-[320px]">
                {children}
              </main>
              <Footer />
            </div>
          </div>
        </DndProvider>
      </body>
    </html>
  );
}
